services:
  cs16-server-net:
    build: .
    image: cs16-server-net
    container_name: cs16-server-net
    init: true
    network_mode: host
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    restart: unless-stopped
