#!/bin/bash

set -euo pipefail

print_help() {
    printf "Usage: %s <build | deploy | start | restart | stop>\n" "${0##*/}"
}

if [[ "${#}" -gt 1 ]]; then
    printf "Only 1 command is accepted\n" 1>&2
    print_help
    exit 1
elif [[ "${#}" -eq 0 ]]; then
    print_help
    exit 0
fi

case "${1}" in
    "build")
        docker build -t cs16-server-net .
        #docker compose build cs16-server-net
        ;;
    "deploy")
        docker run -d --init --network host --name cs16-server-net --restart unless-stopped cs16-server-net
        #docker compose up -d cs16-server-net
        ;;
    "start")
        docker start cs16-server-net
        #docker compose start cs16-server-net
        ;;
    "restart")
        docker restart cs16-server-net
        #docker compose restart cs16-server-net
        ;;
    "stop")
        docker stop cs16-server-net
        #docker compose stop cs16-server-net
        ;;
    *)
        printf "Invalid command: %s\n" "${1}" 1>&2
        print_help
        exit 1
        ;;
esac
