#!/bin/sh

set -e

mkdir libera

[ ! -f irc.pem ] && openssl req \
                            -x509 \
                            -newkey RSA:4096 \
                            -sha256 \
                            -nodes \
                            -days 365000 \
                            -subj "/CN=irc.libera.chat/O=CertFP" \
                            -out libera/libera.pem \
                            -keyout libera/libera.pem

chmod 400 libera/libera.pem

openssl x509 \
        -in libera/libera.pem \
        -noout \
        -fingerprint -sha512 \
    | awk -F= '{gsub(":",""); print tolower ($2)}' > libera/libera.fp

chmod 444 libera/libera.fp

cat libera/libera.fp
