#!/bin/sh

openssl req -x509                             \
        -newkey EC                            \
        -pkeyopt ec_paramgen_curve:prime256v1 \
        -sha256                               \
        -nodes -days 365000                   \
        -subj "/CN=localhost.localdomain"     \
        -keyout key.pem                       \
        -out crt.pem

openssl x509 -in crt.pem -text -noout
