(custom-set-variables
 '(auto-save-default nil)
 '(auto-save-list-file-prefix nil)
 '(column-number-mode t)
 '(global-display-line-numbers-mode t)
 '(make-backup-files nil)
 '(menu-bar-mode nil)
 '(require-final-newline t)
 '(show-paren-mode nil)
 '(show-trailing-whitespace t)
 '(size-indication-mode t)
 '(use-short-answers t)
 ;;'(global-font-lock-mode nil)
 ;;'(global-hl-line-mode t)
)
