export LANG="C.UTF-8"
export EDITOR="mg -n"
#export EDITOR="emacsclient -nw"
#export ALTERNATE_EDITOR="emacs -nw"
export PAGER="less -M"
export MANWIDTH="80"
export LESSHISTFILE="-"
#export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

[[ -f "${HOME}/.bashrc" ]] && . "${HOME}/.bashrc"
