PS1="\h$ "
LANG="C.UTF-8"
EDITOR="mg -n"
#EDITOR="emacsclient -nw"
#ALTERNATE_EDITOR="emacs -nw"
PAGER="less -M"
LESSHISTFILE="-"
HISTFILE=""
#HISTSIZE="10000"
#HISTCONTROL="ignoreboth"

export PS1 LANG EDITOR #ALTERNATE_EDITOR PAGER LESSHISTFILE HISTFILE #HISTSIZE #HISTCONTROL

[[ -f "${HOME}/.bashrc" ]] && . "${HOME}/.bashrc"
