#!/bin/bash

set -euo pipefail

container="golang:trixie"

docker_build() {
    lyrebird_ver="0.6.1"

    tar xvf /src/lyrebird/lyrebird-lyrebird-${lyrebird_ver}.tar.gz -C /build/lyrebird
    cd lyrebird-lyrebird-${lyrebird_ver}
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-X main.lyrebirdVersion=${lyrebird_ver} -w -s" -v -o lyrebird.exe ./cmd/lyrebird
    cp -v lyrebird.exe /src/lyrebird/
}

docker run --rm -v "$(pwd)":/src/lyrebird -w /build/lyrebird "${container}" bash -c "$(declare -f docker_build) && docker_build"
