#!/bin/bash

set -euo pipefail

container="golang:trixie"

docker_build() {
    lyrebird_ver="0.6.1"

    tar xvf /src/lyrebird/lyrebird-lyrebird-${lyrebird_ver}.tar.gz -C /build/lyrebird
    cd lyrebird-lyrebird-${lyrebird_ver}
    CGO_ENABLED=1 go build -ldflags="-X main.lyrebirdVersion=${lyrebird_ver} -w -s" -v -o lyrebird ./cmd/lyrebird
    cp -v lyrebird /src/lyrebird
}

docker run --rm -v "$(pwd)":/src/lyrebird -w /build/lyrebird "${container}" bash -c "$(declare -f docker_build) && docker_build"
