#!/bin/bash

set -euo pipefail

container="golang:trixie"

docker_build() {
    lyrebird_ver="0.6.1"
    lyrebird_url="https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird/-/archive/lyrebird-${lyrebird_ver}/lyrebird-lyrebird-${lyrebird_ver}.tar.gz"

    if ! curl --connect-timeout 10 -LO "${lyrebird_url}"; then
        curl --socks5 127.0.0.1:9150 -LO "${lyrebird_url}"
    fi

    tar xvf lyrebird-lyrebird-${lyrebird_ver}.tar.gz
    cd lyrebird-lyrebird-${lyrebird_ver}
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-X main.lyrebirdVersion=${lyrebird_ver} -w -s" -v -o lyrebird.exe ./cmd/lyrebird
    cp -v lyrebird.exe /src/lyrebird/
}

docker run --rm --network=host -v "$(pwd)":/src/lyrebird -w /build/lyrebird "${container}" bash -c "$(declare -f docker_build) && docker_build"
