services:
  cs16-server-lan:
    build: .
    image: cs16-server-lan
    container_name: cs16-server-lan
    network_mode: host
    init: true
    restart: unless-stopped
    # Not needed with network_mode: host
    #ports:
    #  - "27015:27015/udp"
    #  - "27015:27015/tcp"
