services:
  cs16-server-lan:
    build: .
    image: cs16-server-lan
    container_name: cs16-server-lan
    init: true
    restart: unless-stopped
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
