#!/bin/bash

set -euo pipefail

print_help() {
    printf "Usage: %s <build | deploy | start | restart | stop>\n" "${0##*/}"
}

if [[ "${#}" -gt 1 ]]; then
    printf "Only 1 command is accepted\n" 1>&2
    print_help
    exit 1
elif [[ "${#}" -eq 0 ]]; then
    print_help
    exit 0
fi

case "${1:-}" in
    "build")
        docker build --progress plain -t cs16-server-lan .
        ;;
    "deploy")
        docker run --init -d -p 27015:27015/udp -p 27015:27015 --name cs16-server-lan cs16-server-lan
        ;;
    "start")
        docker start cs16-server-lan
        ;;
    "restart")
        docker restart cs16-server-lan
        ;;
    "stop")
        docker stop cs16-server-lan
        ;;
    *)
        printf "Invalid command: %s\n" "${1}" 1>&2
        print_help
        exit 1
        ;;
esac
