#!/bin/sh

if [ $# -eq 0 ]; then
	exit 0
fi

case $1 in
	-s) ;;
	-w) IS_WORKSTATION=1;;
	*) exit 0;;
esac

set -- curl ssh git xz tar

if [ -n "$IS_WORKSTATION" ]; then
	set -- "$@" gpg dirmngr gpg-agent
fi

for pkg in "$@"; do
	if [ -z "$(command -v "$pkg")" ]; then
		to_install="$to_install $pkg"
	fi
done

if [ -n "$to_install" ]; then
	printf '\nInstall:%s' "$to_install\n\n"
	exit 1
fi

cd ~/ || exit 1

mkdir -m 700 .ssh
mkdir repos

if [ -n "$IS_WORKSTATION" ]; then
	gpg --keyserver hkps://keys.openpgp.org --search-keys 159C66B3104E3E30
	gpg --edit-key 159C66B3104E3E30 trust
	curl -L https://github.com/red-magic/dotfiles/raw/master/extra/archive.tar.xz.gpg -o archive.tar.xz.gpg
	gpg -do archive.tar.xz archive.tar.xz.gpg

	while true; do
		printf 'Continue? [y/n]'
		read -r yn
		case $yn in
			[Yy]*) printf 'Continuing' && break;;
			[Nn]*) printf 'Exiting' && exit 1;;
		esac
	done

	unxz archive.tar.xz
	tar xf archive.tar
	gpg --import archive/gpg/*.*
	cp -f archive/ssh/id_ed25519 .ssh
	cp -f archive/ssh/id_ed25519.pub .ssh
	cp -f archive/ssh/id_ed25519.pub .ssh/authorized_keys
	touch .ssh/known_hosts
	touch .ssh/known_hosts.old
	chmod 600 .ssh/known_hosts*
	rm -rf archive*
else
	curl -LO https://github.com/red-magic.keys
	mv -f red-magic.keys .ssh/authorized_keys
	chmod 400 .ssh/authorized_keys
fi

if [ -f .ssh/id_ed25519 ]; then
	git clone ssh://git@github.com/red-magic/dotfiles repos/dotfiles
else
	git clone https://github.com/red-magic/dotfiles repos/dotfiles
fi

if [ -n "$IS_WORKSTATION" ]; then
	cp -f repos/dotfiles/extra/configs/.gitconfig .
fi

if uname -a | grep -q Linux; then
	cp -f repos/dotfiles/linux/configs/.bash_profile .
	ln -sf .bash_profile .bashrc
elif uname | grep -q BSD; then
	cp -f repos/dotfiles/bsd/configs/.profile .
	if uname | grep -q OpenBSD; then
		cp -f repos/dotfiles/bsd/configs/.mailrc .
	fi
fi

mkdir -p .config/ranger
cp -f repos/dotfiles/extra/configs/.config/ranger/rc.conf .config/ranger
