#!/bin/sh

set -e

print_help() {
    printf "Usage: %s -d <system.img> -c <cd.iso-file>\n" "$(basename "$0")"
}

while getopts :d:c: opt; do
    # -enable-kvm Linux
    # -enable-vvm OpenBSD
    qemu_args="qemu-system-x86_64 -cpu host -smp 16 -m 8G -net nic -net user,hostfwd=tcp::2222-:22 -audio driver=pa,id=pa1,model=hda"
    case $opt in
        c) cd_args="-cdrom $OPTARG" ;;
        d) drive_args="-drive file=$OPTARG,format=raw" ;;
        :) printf "Option -%s requires an argument\n" "$OPTARG" && exit 1 ;;
        *) print_help && exit 1 ;;
    esac
done

if [ -z "$qemu_args" ]; then
    print_help && exit 1
else
    printf "%s %s %s\n" "$qemu_args" "$drive_args" "$cd_args"
    eval "$qemu_args $drive_args $cd_args"
fi
