#!/bin/sh

usage() {
	printf 'Usage: qemu-launch-vm [-d <system-image-file>] [-c <cd-iso-file>]\n'
}

while getopts ":d:c:" arg; do
	qemu_args="qemu-system-x86_64 -cpu host -smp 8 -m 8G -enable-kvm"
	case $arg in
		c) cd_args="-cdrom ${OPTARG}";;
		d) drive_args="-drive file=${OPTARG},format=raw";;
		:) echo "Option -$OPTARG requires an argument" && exit 1;;
		\?) usage && exit 1;;
	esac
done

if [ -z "$qemu_args" ]; then
	usage && exit 1
else
	echo "$qemu_args" "$drive_args" "$cd_args"
	eval "$qemu_args $drive_args $cd_args"
fi
