#!/bin/bash

vows=(a e i o u)
cons=(b c d f g h j k l m n p q r s t v w x y z)

length=8
words=10

cnt=0
while [ "$cnt" -lt $((words)) ]; do
	for ((i=0;i<length;i++)); do
		vowel=${vows[$((RANDOM % ${#vows[@]}))]}
		consonant=${cons[$((RANDOM % ${#cons[@]}))]}
		printf '%s' "$consonant$vowel"
	done

	printf '\n'
	cnt=$((cnt+1))
done
