#!/bin/sh

set -e

ca_cn="Internal CA"
valid_days=7300

mkdir ca

openssl genpkey \
        -algorithm EC \
        -pkeyopt ec_paramgen_curve:secp384r1 \
        -out ca/ca.key

openssl req \
        -x509 \
        -new \
        -nodes \
        -key ca/ca.key \
        -sha384 \
        -days $valid_days \
        -subj "/CN=$ca_cn" \
        -addext "basicConstraints = critical, CA:TRUE" \
        -addext "keyUsage = critical, digitalSignature, keyCertSign, cRLSign" \
        -out ca/ca.crt

chmod 400 ca/ca.key
chmod 444 ca/ca.crt

openssl x509 -in ca/ca.crt -text -noout
