#!/bin/sh

set -e

if [ -z "$1" ]; then
    printf "Usage: %s <domain.internal>\n" "$(basename "$0")"
    exit 1
fi

server_cn=$1

valid_days=3650

rca_cn="RCA"
ica_cn="ICA1"

mkdir "$server_cn"

openssl genpkey \
        -algorithm EC \
        -pkeyopt ec_paramgen_curve:prime256v1 \
        -out "$server_cn"/"$server_cn".key

openssl req \
        -new \
        -key "$server_cn"/"$server_cn".key \
        -subj "/CN=$server_cn" \
        -out "$server_cn"/"$server_cn".csr

cat > "$server_cn"/"$server_cn".ext <<EOF
keyUsage = critical, digitalSignature
extendedKeyUsage = serverAuth
basicConstraints = critical, CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer
subjectAltName = DNS:$server_cn
EOF

openssl x509 \
        -req \
        -in "$server_cn"/"$server_cn".csr \
        -CA "$ica_cn"/"$ica_cn".crt \
        -CAkey "$ica_cn"/"$ica_cn".key \
        -CAcreateserial \
        -sha256 \
        -days $valid_days \
        -extfile "$server_cn"/"$server_cn".ext \
        -out "$server_cn"/"$server_cn".crt

rm -f "$server_cn"/"$server_cn".ext "$server_cn"/"$server_cn".csr "$ica_cn"/"$ica_cn".srl

chmod 400 "$server_cn"/"$server_cn".key
chmod 444 "$server_cn"/"$server_cn".crt

cat "$server_cn"/"$server_cn".crt "$ica_cn"/"$ica_cn".crt > "$server_cn"/"$server_cn".fullchain.pem
cat "$ica_cn"/"$ica_cn".crt "$rca_cn"/"$rca_cn".crt > "$server_cn"/ca-bundle.pem

chmod 444 "$server_cn"/"$server_cn".fullchain.pem

openssl x509 -in "$server_cn"/"$server_cn".crt -text -noout
openssl verify -CAfile "$server_cn"/ca-bundle.pem "$server_cn"/"$server_cn".crt

rm -f "$server_cn"/ca-bundle.pem
