##################
# video settings #
##################

vo=gpu
osd-font='IBM Plex Sans'
sub-font='IBM Plex Sans Condensed'
## = Disable if using with nouveau

screenshot-directory=~/pics/screens/

profile=gpu-hq

hwdec=no
video-sync=display-resample
interpolation=yes
temporal-dither

scale=ewa_lanczossharp
cscale=ewa_lanczossharp 
dscale=ewa_lanczossharp
tscale=oversample

glsl-shader="~/.config/mpv/shaders/antiring.hook"
glsl-shader="~/.config/mpv/shaders/LumaSharpenHook.glsl"
glsl-shader="~/.config/mpv/shaders/filmgrain.glsl"
#glsl-shader="~/.config/mpv/shaders/SSimSuperRes.glsl"
#glsl-shader="~/.config/mpv/shaders/adaptive-sharpen.glsl"
#glsl-shader="~/.config/mpv/shaders/KrigBilateral.glsl"
#glsl-shader="~/.config/mpv/shaders/noise_static_chroma.hook"
#glsl-shader="~/.config/mpv/shaders/noise_static_luma.hook"
#glsl-shader="~/.config/mpv/shaders/noise.glsl"
#glsl-shader="~/.config/mpv/shaders/filmgrain-smooth.glsl"
#glsl-shader="~/.config/mpv/shaders/deband.glsl"

deband=yes #Deactivate deband
deband-iterations=4 #Deband steps (More = Better quality, but higher GPU cost)
deband-range=8 #Deband range (More = Less banding, but higher GPU cost)
#deband-threshold=64 #Deband strength (More = Less banding, but more detail loss)
#deband-grain=64 #Dynamic Grain (More = More dynamic grain)
