#!/bin/bash

mono_dark() {
	ttyColors=(
		000000
		9E9E9E
		9E9E9E
		9E9E9E
		9E9E9E
		9E9E9E
		9E9E9E
		9E9E9E
		000000
		9E9E9E
		9E9E9E
		9E9E9E
		9E9E9E
		9E9E9E
		9E9E9E
		9E9E9E
	)
}

mono_light() {
	ttyColors=(
		F5F5F5
		212121
		212121
		212121
		212121
		212121
		212121
		212121
		F5F5F5
		212121
		212121
		212121
		212121
		212121
		212121
		212121
	)
}

neon_dark() {
	ttyColors=(
		000000
		B0003A
		B0003A
		B0003A
		673AB7
		B0003A
		00BCD4
		AEAEAE
		000000
		B0003A
		B0003A
		B0003A
		673AB7
		B0003A
		00BCD4
		AEAEAE
	)
}

set_tty_color() {
	echo -en "\e]P0${ttyColors[0]}"	 # Background
	echo -en "\e]P1${ttyColors[1]}"  # Red
	echo -en "\e]P2${ttyColors[2]}"  # Green
	echo -en "\e]P3${ttyColors[3]}"  # Yellow
	echo -en "\e]P4${ttyColors[4]}"  # Blue
	echo -en "\e]P5${ttyColors[5]}"  # Magenta
	echo -en "\e]P6${ttyColors[6]}"  # Cyan
	echo -en "\e]P7${ttyColors[7]}"  # White
	echo -en "\e]P8${ttyColors[8]}"  # Black
	echo -en "\e]P9${ttyColors[9]}"  # Red
	echo -en "\e]PA${ttyColors[10]}" # Green
	echo -en "\e]PB${ttyColors[11]}" # Yellow
	echo -en "\e]PC${ttyColors[12]}" # Blue
	echo -en "\e]PD${ttyColors[13]}" # Magenta
	echo -en "\e]PE${ttyColors[14]}" # Cyan
	echo -en "\e]PF${ttyColors[15]}" # White
}

"$@"

if [[ -n "$1" ]]; then
	for i in {1..6}; do
		set_tty_color > /dev/tty"${i}"
	done
	else
	echo "Choose tty color"
fi
