[server]
libera.addresses = "irc.libera.chat/6697"
libera.tls = on
libera.sasl_mechanism = plain
libera.sasl_username = "username"
libera.sasl_password = "password"
libera.nicks = "username,username_,username__"
libera.username = "username"
