[server]
libera.addresses = "irc.libera.chat/6697"
libera.tls = on
libera.sasl_mechanism = plain
libera.sasl_username = "username"
libera.sasl_password = "${sec.data.libera_password}"
libera.nicks = "nickname,nickname_,nickname__"
libera.username = "username"

# /secure passphrase <passphrase>
# /secure set libera_password <password>
