#!/bin/bash

if [[ ! $EUID -eq 0  ]]; then
	echo "Run under root or use sudo"
	exit 1
fi

if ! ldconfig -p | grep libgcc | grep -q '(libc6)'; then
	echo "Enable multilib repo and install lib32-gcc-libs"
	exit 1
fi

packages=(bash tar gzip unzip curl screen)

for pkg in "${packages[@]}"; do
	if  [[ -z "$(command -v "$pkg")" ]]; then
		to_install="$to_install $pkg"
	fi
done

if [[ -n $to_install ]]; then
	echo Install:"$to_install";
	exit 1
fi

export server_user=steam
steam_dir=/home/$server_user/.steam
server_dir=$steam_dir/cs16

if ! grep -q $server_user /etc/passwd; then
	useradd -m -s /bin/bash $server_user
	passwd -dl $server_user
fi

steam_setup_stage_one() {
	mkdir ~/.steam
	ln -sfv ~/.steam ~/.steam/steam
	cd ~/.steam || exit
	
	curl -LO https://www.amxmodx.org/release/metamod-1.21.1-am.zip
	curl -LO https://www.amxmodx.org/release/amxmodx-1.8.2-base-linux.tar.gz
	curl -LO https://www.amxmodx.org/release/amxmodx-1.8.2-cstrike-linux.tar.gz
	curl -LO https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz
	curl -LO https://github.com/APGRoboCop/podbot_mm/releases/download/V3B24-APG/podbot_full_V3B24.zip
	
	for arc in *.tar.gz; do tar xvf "$arc"; done
	for arc in *.zip; do unzip "$arc"; done
	
	mv -vf podbot addons
}

steam_setup_stage_two() {
	cd ~/.steam || exit
	mv -vf addons cs16/cstrike
	ln -sfv ~/.steam/linux32 ~/.steam/sdk32
	
	cat << EOF > cs16/cstrike/addons/metamod/plugins.ini
	linux addons/amxmodx/dlls/amxmodx_mm_i386.so
	linux addons/podbot/podbot_mm.so
EOF
	
	touch cs16/cstrike/{listip.cfg,banned.cfg}
	sed -i 's/gamedll_linux \"dlls\/cs.so\"/gamedll_linux \"addons\/metamod\/dlls\/metamod.so\"/g' cs16/cstrike/liblist.gam
	rm -vf ./*.zip ./*.tar.gz
}

cat << EOF > /usr/bin/cs16server
#!/bin/bash 

if [[ ! \$EUID -eq 0  ]]; then
	echo "Run under root or use sudo."
	exit 1
fi

server_user=$server_user
steam_dir=/home/\$server_user/.steam
server_dir=\$steam_dir/cs16
server_params="-game cstrike -pingboost 3 -maxplayers 16 -secure -autoupdate +map de_dust2"

case \$1 in
		"start")
			su "\$server_user" -c "cd \$server_dir && ./hlds_run \$server_params"
			;;

		"restart")
			su "\$server_user" -c "kill \$(pgrep hlds_linux)"
			;;

		"stop")
			su "\$server_user" -c "kill \$(pgrep hlds_run)"
			su "\$server_user" -c "kill \$(pgrep hlds_linux)"
			;;

		"start-background")
			su "\$server_user" -c "cd \$server_dir && ./hlds_run \$server_params &> /dev/null &"
			;;

		"start-screen")
			su "\$server_user" -c "cd \$server_dir && screen -m -d -S cs16 ./hlds_run \$server_params"
			;;

		"restart-screen")
			su "\$server_user" -c "cd \$server_dir && kill \$(pgrep screen)"
			su "\$server_user" -c "cd \$server_dir && screen -m -d -S cs16 ./hlds_run \$server_params"
			;;

		"stop-screen")
			su "\$server_user" -c "kill \$(pgrep screen)"
			;;

		"update")
		su "\$server_user" -c "cd \$steam_dir && ./steamcmd.sh +force_install_dir \$server_dir +login anonymous +app_update 90 validate +quit"
		su "\$server_user" -c "sed -i 's/gamedll_linux \"dlls\/cs.so\"/gamedll_linux \"addons\/metamod\/dlls\/metamod.so\"/g' ~/.steam/cs16/cstrike/liblist.gam"
			;;

		"screen")
		su "\$server_user" -c "screen -r"
			;;
esac
EOF

chmod -v 755 /usr/bin/cs16server

export -f steam_setup_stage_one steam_setup_stage_two

su $server_user -c steam_setup_stage_one

for ((i=0;i<3;i++)); do su $server_user -c "cd $steam_dir && ./steamcmd.sh +force_install_dir $server_dir +login anonymous +app_update 90 validate +quit"; done

su $server_user -c steam_setup_stage_two
