#!/bin/bash
#
# Eventually prints FALSE.
# Works alright with:
# grep -q 'libc.so.6' < <(ldconfig -p)
# and
# ldconfig -p | grep 'libc.so.6' &> /dev/null
#
# ldconfig -p | grep -q 'libstdc++.so.6 (libc6)'
# may just straight print FALSE without
# even entering the while cycle.

set -euo pipefail

x=0

while ldconfig -p | grep -q 'libc.so.6'; do
    echo "$((x++))"
done

echo "FALSE"
