#!/bin/sh

set -e

ca_cn="Internal CA"
ca_name="internal-ca"
valid_days=7300

mkdir "$ca_name"

openssl genpkey \
        -algorithm RSA \
        -pkeyopt rsa_keygen_bits:4096 \
        -out "$ca_name"/"$ca_name".key

openssl req \
        -x509 \
        -new \
        -nodes \
        -key "$ca_name"/"$ca_name".key \
        -sha256 \
        -days $valid_days \
        -subj "/CN=$ca_cn" \
        -addext "keyUsage = critical, keyCertSign, cRLSign" \
        -addext "basicConstraints = critical, CA:TRUE, pathlen:1" \
        -addext "subjectKeyIdentifier = hash" \
        -out "$ca_name"/"$ca_name".crt

chmod 400 "$ca_name"/"$ca_name".key
chmod 444 "$ca_name"/"$ca_name".crt

openssl x509 -in "$ca_name"/"$ca_name".crt -text -noout
