#!/bin/sh

set -e

if [ -z "$1" ]; then
    printf "Usage: %s <domain.internal>\n" "$(basename "$0")"
    exit 1
fi

ca_name="internal-ca"
intermediate_name="internal-intermediate-1"
server_cn=$1
valid_days=3650

mkdir "$server_cn"

openssl genpkey \
        -algorithm RSA \
        -pkeyopt rsa_keygen_bits:4096 \
        -out "$server_cn"/"$server_cn".key

cat > "$server_cn"/"$server_cn".ext <<EOF
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
basicConstraints = critical, CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer
subjectAltName = DNS:$server_cn
EOF

openssl req \
        -new \
        -key "$server_cn"/"$server_cn".key \
        -subj "/CN=$server_cn" \
        -out "$server_cn"/"$server_cn".csr

openssl x509 \
        -req \
        -in "$server_cn"/"$server_cn".csr \
        -CA "$intermediate_name"/"$intermediate_name".crt \
        -CAkey "$intermediate_name"/"$intermediate_name".key \
        -CAcreateserial \
        -sha256 \
        -days $valid_days \
        -extfile "$server_cn"/"$server_cn".ext \
        -out "$server_cn"/"$server_cn".crt

rm -f "$server_cn"/"$server_cn".ext "$server_cn"/"$server_cn".csr "$intermediate_name"/"$intermediate_name".srl

chmod 400 "$server_cn"/"$server_cn".key
chmod 444 "$server_cn"/"$server_cn".crt

cat "$server_cn"/"$server_cn".crt "$intermediate_name"/"$intermediate_name".crt > "$server_cn"/"$server_cn".fullchain.pem
cat "$intermediate_name"/"$intermediate_name".crt "$ca_name"/"$ca_name".crt > "$server_cn"/ca-bundle.pem

chmod 444 "$server_cn"/"$server_cn".fullchain.pem

openssl x509 -in "$server_cn"/"$server_cn".crt -text -noout
openssl verify -CAfile "$server_cn"/ca-bundle.pem "$server_cn"/"$server_cn".crt

rm -f "$server_cn"/ca-bundle.pem
