#!/bin/sh

server_user=steam

if [ "$(id -un)" != "$server_user" ]; then
	printf 'You must run this as %s user\n' "$server_user"
	exit 1
fi

if [ ! -f maps-and-wpts.tar.xz ]; then
	printf 'maps-and-wpts.tar.xz must be in the same directory where the script is\n'
	exit 1
fi

tar xvf maps-and-wpts.tar.xz

cp -vr maps-and-wpts/cstrike/* /home/$server_user/.steam/cs16/cstrike
cp -v maps-and-wpts/podbot-waypoints/* /home/$server_user/.steam/cs16/cstrike/addons/podbot/wptdefault

cat maps-and-wpts/map-list >> /home/$server_user/.steam/cs16/cstrike/addons/amxmodx/configs/maps.ini
