#!/bin/sh

# Map pack
# https://archive.org/details/cs-1.6-mega-map-pack-v-2018.1.7z

server_user=steam

if [ "$(id -un)" != "$server_user" ]; then
	printf 'You must run this as %s user\n' "$server_user"
	exit 1
fi

if [ ! -f maps-and-wpts.tar.xz ]; then
	printf 'maps-and-wpts.tar.xz must be in the same directory where the script is\n'
	exit 1
fi

tar xvf maps-and-wpts.tar.xz

cp -vr maps-and-wpts/cstrike/* /home/$server_user/.steam/cs16/cstrike
cp -v maps-and-wpts/podbot-waypoints/* /home/$server_user/.steam/cs16/cstrike/addons/podbot/wptdefault

# Add all maps
cat maps-and-wpts/map-list >> /home/$server_user/.steam/cs16/cstrike/addons/amxmodx/configs/maps.ini

# Add maps only with podbot waypoints
#for map in /home/"$server_user"/.steam/cs16/cstrike/addons/podbot/wptdefault/*; do
#	printf '%s\n' "$(basename "${map%.*}")";
#done | uniq >> /home/$server_user/.steam/cs16/cstrike/addons/amxmodx/configs/maps.ini
