#!/bin/bash

vows=(a e i o u)
cons=(b c d f g h j k l m n p q r s t v w x y z)

for i in {1..20}; do
for i in { $(($RANDOM % 4 + 0 )) }; do

for i in ${vows[ $(( $RANDOM % 5 + 0 )) ]}; do
	for j in ${cons[ $(( $RANDOM % 21 + 0 )) ]}; do
		echo -n $i$j
	done
done

done
echo
done
