#!/bin/sh

cp -f ~/themes/amber/.Xresources ~/.Xresources
cp -f ~/themes/amber/i3/config ~/.config/i3/config
cp -f ~/themes/amber/polybar/config ~/.config/polybar/config
cp -f ~/themes/amber/.gtkrc-2.0 ~/.gtkrc-2.0
cp -f ~/themes/amber/settings.ini ~/.config/gtk-3.0/settings.ini
xrdb ~/.Xresources
i3-msg restart
