#!/bin/bash

container="rust:slim-trixie"

docker_build() {
    set -euo pipefail

    arti_ver="1.5.0"
    arti_url="https://gitlab.torproject.org/tpo/core/arti/-/archive/arti-v${arti_ver}/arti-arti-v${arti_ver}.tar.gz"

    apt-get update -y
    apt-get install -y mingw-w64 pkg-config libssl-dev libsqlite3-dev curl

    if ! curl --socks5 127.0.0.1:9150 -LO "${arti_url}"; then
        curl --connect-timeout 10 -LO "${arti_url}"
    fi

    tar xvf arti-arti-v${arti_ver}.tar.gz
    cd arti-arti-v${arti_ver}
    rustup target add x86_64-pc-windows-gnu
    cargo build -p arti --locked --release --target x86_64-pc-windows-gnu --features static
    strip -sv target/x86_64-pc-windows-gnu/release/arti.exe
    cp -v target/x86_64-pc-windows-gnu/release/arti.exe /out
}

docker run --rm --network=host -v "$(pwd)":/out -w /build "${container}" bash -c "$(declare -f docker_build) && docker_build"
