#!/bin/bash

container="rust:slim-trixie"

docker_build() {
    set -euo pipefail

    arti_ver="1.5.0"
    arti_url="https://gitlab.torproject.org/tpo/core/arti/-/archive/arti-v${arti_ver}/arti-arti-v${arti_ver}.tar.gz"

    apt-get update -y
    apt-get install -y pkg-config libssl-dev libsqlite3-dev curl

    if ! curl --socks5 127.0.0.1:9150 -LO "${arti_url}"; then
        curl --connect-timeout 10 -LO "${arti_url}"
    fi

    tar xvf arti-arti-v${arti_ver}.tar.gz
    cd arti-arti-v${arti_ver}
    cargo build -p arti --locked --release
    strip -sv target/release/arti
    cp -v target/release/arti /src/arti
}

docker run --rm --network=host -v "$(pwd)":/src/arti -w /build/arti "${container}" bash -c "$(declare -f docker_build) && docker_build"
