#!/bin/bash

echo "Downloading Cloudflare IPv4 List"
mapfile -t cf_ips < <(curl "https://www.cloudflare.com/ips-v4")

for ip in "${cf_ips[@]}"; do
    echo "Adding ${ip}"
    sudo firewall-cmd --permanent --zone=drop --add-rich-rule 'rule family="ipv4" source address="${ip}" port port=443 protocol=tcp accept';
done

echo "Adding SSH port"
sudo firewall-cmd --permanent --zone=drop --add-port=22/tcp

echo "Reloading firewall"
sudo firewall-cmd --reload

echo "Setting default zone to drop"
sudo firewall-cmd --set-default-zone=drop
