#!/bin/bash

printf "Downloading Cloudflare IPv4 List\n"
mapfile -t cf_ips < <(curl -LO "https://www.cloudflare.com/ips-v4")

for ip in "${cf_ips[@]}"; do
    printf "Adding %s" "${ip}"
    sudo firewall-cmd --permanent --zone=drop --add-rich-rule 'rule family="ipv4" source address="${ip}" port port=443 protocol=tcp accept'
done

printf "Adding SSH port\n"
sudo firewall-cmd --permanent --zone=drop --add-port=22/tcp

printf "Reloading firewall\n"
sudo firewall-cmd --reload

printf "Setting default zone to drop\n"
sudo firewall-cmd --set-default-zone=drop
