#!/bin/bash

aurpkgs=(
    "pacproxy-bin"
    "simple-and-soft-cursor"
    "snowflake-pt-client-bin"
    "tor-relay-scanner-bin"
    "tty-colorscheme"
    "windows-10-cursor"
    "ttf-go"
)

mkdir -v "/home/${USER}/repos/aur"

for aurpkg in "${aurpkgs[@]}"; do
    git clone "ssh://aur@aur.archlinux.org/${aurpkg}" "/home/${USER}/repos/aur/${aurpkg}"
done
