#!/bin/bash

set -euo pipefail

aur_pkgs=(
    "pacproxy-bin"
    "simple-and-soft-cursor"
    "snowflake-pt-client-bin"
    "tor-relay-scanner-bin"
    "ttf-go"
    "tty-colorscheme"
    "windows-10-cursor"
)

aur_dir="/home/${USER}/repos/aur"

if [[ -d "${aur_dir}" ]]; then
    printf "Directory %s already exists\n" "${aur_dir}"
    exit 1
fi

mkdir -v "${aur_dir}"

for aur_pkg in "${aur_pkgs[@]}"; do
    git clone "ssh://aur@aur.archlinux.org/${aur_pkg}" "${aur_dir}/${aur_pkg}"
done
