#!/bin/bash

cs_dir="/etc/tty-colorscheme/colorschemes"

cs_help() {
    printf "Usage: %s [-lps | colorscheme]\n" "$(basename "$0")"
    printf "  -l    list colorschemes\n"
    printf "  -p    print current palette\n"
    printf "  -s    shift through colorschemes and fonts\n"
}

cs_list() {
    for cs_name in "${cs_dir}"/*; do
        basename "${cs_name}"
    done
}

cs_palette() {
    cnt=0
    for bkgrnd in {40..47}; do
        printf "\e[%sm" "${bkgrnd}"
        for bold in 22 1; do
            printf "\e[%sm" "${bold}"
            for frgrnd in {30..37}; do
                printf "\e[%sm %3s" "${frgrnd}" "${cnt}"
                ((cnt++))
            done
        done
        printf "\e[0m\n"
    done
}

cs_shift() {
    mapfile -t cs_arr < <(cs_list)
    max_ind_cs="$((${#cs_arr[@]}-1))"
    ind_cs=-1

    get_fonts() {
        find /usr/share/kbd/consolefonts/*.psf* -exec file {} + \
            | grep -E 'PC Screen Font | gzip' \
            | cut -d: -f 1
    }

    mapfile -t fnt_arr < <(get_fonts)
    max_ind_fnt="$((${#fnt_arr[@]}-1))"
    ind_fnt=-1

    while true; do
        if [[ "${ind_fnt}" -gt -1 ]]; then
            fnt="${fnt_arr[${ind_fnt}]}"
            setfont "${fnt}" > /dev/null 2>&1
        fi

        if [[ "${ind_cs}" -gt -1 ]]; then
            cs="${cs_arr[${ind_cs}]}"
            $(basename "$0") "${cs}"
        else
            clear
            cs_palette
        fi

        if [[ "${ind_fnt}" -gt -1 ]]; then
            printf "Setting %s font\n" "$(basename "${fnt}")"
        fi

        printf "\nUse j and k keys to shift through colorschemes\n"
        printf "Use h and l keys to shift through fonts\n"

        read -rsn1
        case "${REPLY}" in
            j) [[ "${ind_cs}" -lt "${max_ind_cs}" ]] && ((ind_cs++)) ;;
            k) [[ "${ind_cs}" -gt 0 ]] && ((ind_cs--)) ;;
            l) [[ "${ind_fnt}" -lt "${max_ind_fnt}" ]] && ((ind_fnt++)) ;;
            h) [[ "${ind_fnt}" -gt 0 ]] && ((ind_fnt--)) ;;
            *) exit 0 ;;
        esac
    done
}

cs_set() {
    cs_file="${cs_dir}/$1"
    [[ ! -f "${cs_file}" ]] && printf "Invalid colorscheme: %s\n" "$1" && exit 1
    source "${cs_file}"

    set_colors() {
        printf "\e]P0%s" "${color01:?}" # Black (Background)
        printf "\e]P1%s" "${color02:?}" # Red
        printf "\e]P2%s" "${color03:?}" # Green
        printf "\e]P3%s" "${color04:?}" # Yellow
        printf "\e]P4%s" "${color05:?}" # Blue
        printf "\e]P5%s" "${color06:?}" # Magenta
        printf "\e]P6%s" "${color07:?}" # Cyan
        printf "\e]P7%s" "${color08:?}" # White (Foreground)
        printf "\e]P8%s" "${color09:?}" # Black
        printf "\e]P9%s" "${color10:?}" # Red
        printf "\e]PA%s" "${color11:?}" # Green
        printf "\e]PB%s" "${color12:?}" # Yellow
        printf "\e]PC%s" "${color13:?}" # Blue
        printf "\e]PD%s" "${color14:?}" # Magenta
        printf "\e]PE%s" "${color15:?}" # Cyan
        printf "\e]PF%s" "${color16:?}" # White
    }

    for i in {1..6}; do
        set_colors > "/dev/tty${i}"
    done > /dev/null 2>&1

    [[ "${TERM}" == "linux" ]] && clear && $(basename "$0") -p
    printf "Setting %s colorscheme\n" "$1"
}

while getopts ":lps" opt; do
    case "${opt}" in
        l)
            cs_list
            exit 0
            ;;
        p)
            cs_palette
            exit 0
            ;;
        s)
            cs_shift
            exit 0
            ;;
        *)
            printf "Invalid option -%s\n" "${OPTARG}"
            cs_help
            exit 1
            ;;
    esac
done

[[ "$#" -eq 1 ]] && cs_set "$1" && exit 0

cs_help
