#!/bin/bash

start() {
	for i in {1..6}; do
		echo -en "\e]P0efebe9" > /dev/tty"${i}" # Background
		echo -en "\e]P13e2723" > /dev/tty"${i}" # Red
		echo -en "\e]P23e2723" > /dev/tty"${i}" # Green
		echo -en "\e]P33e2723" > /dev/tty"${i}" # Yellow
		echo -en "\e]P43e2723" > /dev/tty"${i}" # Blue
		echo -en "\e]P53e2723" > /dev/tty"${i}" # Magenta
		echo -en "\e]P63e2723" > /dev/tty"${i}" # Cyan
		echo -en "\e]P73e2723" > /dev/tty"${i}" # White
		echo -en "\e]P8efebe9" > /dev/tty"${i}" # Black
		echo -en "\e]P93e2723" > /dev/tty"${i}" # Red
		echo -en "\e]PA3e2723" > /dev/tty"${i}" # Green
		echo -en "\e]PB3e2723" > /dev/tty"${i}" # Yellow
		echo -en "\e]PC3e2723" > /dev/tty"${i}" # Blue
		echo -en "\e]PD3e2723" > /dev/tty"${i}" # Magenta
		echo -en "\e]PE3e2723" > /dev/tty"${i}" # Cyan
		echo -en "\e]PF3e2723" > /dev/tty"${i}" # White
	done
}; start 
