#!/bin/sh

set -e

ca_c="AQ"
ca_o="Internal"
ca_cn="RCA"

valid_days=7300

mkdir "$ca_cn"

openssl genpkey \
        -algorithm EC \
        -pkeyopt ec_paramgen_curve:secp384r1 \
        -out "$ca_cn"/"$ca_cn".key

openssl req \
        -x509 \
        -new \
        -nodes \
        -key "$ca_cn"/"$ca_cn".key \
        -sha384 \
        -days $valid_days \
        -subj "/C=$ca_c/O=$ca_o/CN=$ca_cn" \
        -addext "keyUsage = critical, keyCertSign, cRLSign" \
        -addext "basicConstraints = critical, CA:TRUE, pathlen:1" \
        -addext "subjectKeyIdentifier = hash" \
        -out "$ca_cn"/"$ca_cn".crt

chmod 400 "$ca_cn"/"$ca_cn".key
chmod 444 "$ca_cn"/"$ca_cn".crt

openssl x509 -in "$ca_cn"/"$ca_cn".crt -text -noout
