#!/bin/bash

case "${1}" in
    "build")
        docker build --progress plain -t cs16-server-lan .
        ;;
    "deploy")
        docker run --init -d -p 27015:27015/udp -p 27015:27015 --name cs16-server-lan cs16-server-lan
        ;;
    "start")
        docker start cs16-server-lan
        ;;
    "stop")
        docker stop cs16-server-lan
        ;;
esac
