#!/bin/sh

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <domain.internal>"
    exit 1
fi

domain=$1

mkdir "$domain"

openssl req \
        -x509 \
        -newkey RSA:4096 \
        -sha256 \
        -nodes \
        -days 3650 \
        -subj "/CN=$domain" \
        -addext "subjectAltName = DNS:$domain" \
        -keyout "$domain"/"$domain".key \
        -out "$domain"/"$domain".crt

chmod 400 "$domain"/"$domain".key
chmod 444 "$domain"/"$domain".crt

openssl x509 -in "$domain"/"$domain".crt -text -noout
