#!/bin/sh

set -e

domain="domain.localdomain"
ip="123.123.123.123"

openssl req -x509 \
        -newkey RSA:4096 \
        -sha256 \
        -nodes \
        -days 365000 \
        -subj "/CN=$domain" \
        -addext "subjectAltName = DNS:$domain, IP:$ip" \
        -keyout rsa-key.pem \
        -out rsa-crt.pem

chmod 400 rsa-key.pem
chmod 444 rsa-crt.pem

openssl x509 -in rsa-crt.pem -text -noout
