#!/bin/sh

set -e

domain="domain.internal"

openssl req -x509 \
        -newkey EC \
        -pkeyopt ec_paramgen_curve:prime256v1 \
        -sha256 \
        -nodes \
        -days 365000 \
        -subj "/CN=$domain" \
        -addext "subjectAltName = DNS:$domain" \
        -keyout $domain.key \
        -out $domain.crt

chmod 400 $domain.key
chmod 444 $domain.crt

openssl x509 -in $domain.crt -text -noout
