#!/bin/sh

set -e

if [ -z "$1" ]; then
    printf "Usage: %s <domain.internal>\n" "$(basename "$0")"
    exit 1
fi

domain=$1

mkdir "$domain"

openssl req \
        -x509 \
        -newkey RSA \
        -pkeyopt rsa_keygen_bits:4096 \
        -sha256 \
        -nodes \
        -days 1825 \
        -subj "/CN=$domain" \
        -addext "keyUsage = critical, digitalSignature, keyEncipherment" \
        -addext "extendedKeyUsage = serverAuth" \
        -addext "basicConstraints = critical, CA:FALSE" \
        -addext "subjectKeyIdentifier = hash" \
        -addext "subjectAltName = DNS:$domain" \
        -set_serial 0x"$(openssl rand -hex 16)" \
        -keyout "$domain"/"$domain".key \
        -out "$domain"/"$domain".crt

chmod 400 "$domain"/"$domain".key
chmod 444 "$domain"/"$domain".crt

openssl x509 -in "$domain"/"$domain".crt -text -noout
