#!/bin/sh

cp -f ~/themes/clouds/.Xresources ~/.Xresources
cp -f ~/themes/clouds/i3/config ~/.config/i3/config
cp -f ~/themes/clouds/polybar/config ~/.config/polybar/config
cp -f ~/themes/clouds/.gtkrc-2.0 ~/.gtkrc-2.0
cp -f ~/themes/clouds/settings.ini ~/.config/gtk-3.0/settings.ini
pkill compton
xrdb ~/.Xresources
i3-msg restart
