#!/bin/sh

if [ "$(id -u)" -ne 0  ]; then
	printf '\nUse sudo to run this script\n\n'
	exit 1
fi

if ! ldconfig -p | grep libgcc | grep -q '(libc6)'; then
	printf '\nInstall lib32-gcc-libs\n\n'
	exit 1
fi

set -- sudo tar xz gzip unzip curl

for pkg in "$@"; do
	if  [ -z "$(command -v "$pkg")" ]; then
		to_install="$to_install $pkg"
	fi
done

if [ -n "$to_install" ]; then
	printf '\nInstall%s\n\n' "$to_install"
	exit 1
fi

server_user=steam
server_conf=/etc/cs16-server/cs16-server.conf

useradd -m $server_user
passwd -dl $server_user

install -vm 755 cs16-server -t /usr/bin
install -vDm 644 cs16-server.conf "$server_conf"

sed -i "s|server_user=|server_user=$server_user|" /usr/bin/cs16-server
sed -i "s|server_conf=|server_conf=$server_conf|" /usr/bin/cs16-server

cp -vf stage-two /tmp/stage-two.tmp

sudo -u $server_user /tmp/stage-two.tmp

rm -vf /tmp/stage-two.tmp

if [ -x "$(command -v systemctl)" ]; then
	install -vm 644 cs16-server.service -t /usr/lib/systemd/system
fi

# Notes
#
# Admin access
# [cstrike/addons/amxmodx/configs/users.ini]
# "STEAM_0:0:YOUR_STEAM_ID" "" "abcdefghijklmnopqrstuv" "ce"
# [console]
# bind "]" "amxmodmenu"
#
# Podbots 
# [cstrike/addons/podbot/podbot.cfg]
# pb_password="your_password"
# [console]
# bind "[" "pb menu"
# setinfo _pbadminpw "your_password"
#
# Additional config
# [server.cfg]
# mp_timelimit 0
# mp_freezetime 0
# mp_buytime 10
# mp_startmoney 16000
