#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	printf '\nUse sudo to run this script\n\n'
	exit 1
fi

if [ -n "$(command -v pacman)" ]; then
	if [ ! -d /usr/lib32 ] || [ "$(find /usr/lib32 -type f | grep libstdc++)" = "" ] ; then
		printf '\nInstall 32 bit libstdc++\n'
		printf 'Read README.md for info\n\n'
		exit 1
	fi
fi

if [ -n "$(command -v apt)" ]; then
	if [ "$(find /usr/lib32 -type f | grep libstdc++)" = "" ]; then
		printf '\nInstall 32 bit libstdc++\n'
		printf 'Read README.md for info\n\n'
		exit 1
	fi
fi

if [ -n "$(command -v dnf)" ]; then
	if [ "$(find /usr/lib -type f | grep libstdc++)" = "" ] ; then
		printf '\nInstall 32 bit libstdc++\n'
		printf 'Read README.md for info\n\n'
		exit 1
	fi
fi

set -- sudo tar xz gzip unzip curl

for pkg in "$@"; do
	if  [ -z "$(command -v "$pkg")" ]; then
		to_install="$to_install $pkg"
	fi
done

if [ -n "$to_install" ]; then
	printf '\nInstall%s\n\n' "$to_install"
	exit 1
fi

mkdir -vm 755 /tmp/cs16-server

set -- \
https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz \
https://github.com/Bots-United/metamod-p/releases/download/v1.21p38/metamod_i686_linux_win32-1.21p38.tar.xz \
https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz \
https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz \
https://github.com/APGRoboCop/podbot_mm/releases/download/V3B24-APG/podbot_full_V3B24.zip

for link in "$@"; do
	printf "==> Downloading %s\n" "$link"
	curl -fLO "$link" --output-dir /tmp/cs16-server && continue
	printf "Failed downloading %s\n" "$link"
	exit 1
done

chmod -v 644 /tmp/c16-server/*

server_user=steam
server_conf=/etc/cs16-server/cs16-server.conf

useradd -m -s /bin/bash $server_user
passwd -dl $server_user

install -vm 755 cs16-server -t /usr/bin
install -vDm 644 cs16-server.conf "$server_conf"

sed -i "s|server_user=|server_user=$server_user|" /usr/bin/cs16-server
sed -i "s|server_conf=|server_conf=$server_conf|" /usr/bin/cs16-server

cp -vf stage-two /tmp/stage-two.tmp
chmod -v 755 /tmp/stage-two.tmp

sudo -u $server_user /tmp/stage-two.tmp

rm -vf /tmp/stage-two.tmp

if [ -x "$(command -v systemctl)" ]; then
	install -vm 644 cs16-server.service -t /usr/lib/systemd/system
fi

printf '\nInstallation completed\n\n'

# Notes
#
# Admin access
# [cstrike/addons/amxmodx/configs/users.ini]
# "STEAM_0:0:YOUR_STEAM_ID" "" "abcdefghijklmnopqrstuv" "ce"
# [console]
# bind "]" "amxmodmenu"
#
# Podbots 
# [cstrike/addons/podbot/podbot.cfg]
# pb_password="your_password"
# [console]
# bind "[" "pb menu"
# setinfo _pbadminpw "your_password"
#
# Additional config
# [server.cfg]
# mp_timelimit 0
# mp_freezetime 0
# mp_buytime 10
# mp_startmoney 16000
