#!/bin/sh

cd "/home/$USER" || exit

mkdir ~/.steam
ln -sfv ~/.steam ~/.steam/steam

cd ~/.steam || exit

# Steamcmd
curl -LO https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz

# Metamod 1.21.1 release, Amxmodx 1.10 latest
# With Amxmodx 1.10 server hangs after some time
curl -LO https://www.amxmodx.org/release/metamod-1.21.1-am.zip
curl -LO https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz
curl -LO https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz

# Amxmodx 1.8.2 relese, crashes
#curl -LO https://www.amxmodx.org/release/amxmodx-1.8.2-base-linux.tar.gz
#curl -LO https://www.amxmodx.org/release/amxmodx-1.8.2-cstrike-linux.tar.gz

# Podbots
curl -LO https://github.com/APGRoboCop/podbot_mm/releases/download/V3B24-APG/podbot_full_V3B24.zip

for arc in *.tar.gz; do tar xvf "$arc"; done
for arc in *.zip; do unzip "$arc"; done

mv -vf podbot addons

cnt=0
while [ $((cnt)) -lt 3 ]; do 
	# Update needs to be run a few times to download and validate everything
	./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit
	cnt=$((cnt+1))
done

mv -vf addons cs16/cstrike
ln -sfv ~/.steam/linux32 ~/.steam/sdk32

printf 'linux addons/amxmodx/dlls/amxmodx_mm_i386.so\n' >> cs16/cstrike/addons/metamod/plugins.ini
printf 'linux addons/podbot/podbot_mm.so\n' >> cs16/cstrike/addons/metamod/plugins.ini

# Create cfg files so steamcmd won't complain
touch cs16/cstrike/listip.cfg
touch cs16/cstrike/banned.cfg

rm -vf ./*.zip ./*.tar.gz
