[global]
server role = standalone server
security = user
server smb encrypt = required
server signing = mandatory

[storage]
path = /srv/samba
valid users = smbuser
writable = yes
create mask = 0644
directory mask = 0755

; pw useradd -d /nonexistent -s /usr/sbin/nologin -c "Samba User" smbuser
; pdbedit -a -u smbuser
; testparm /usr/local/etc/smb4.conf
; Reboot before starting samba service
