server:
    # Run unbound-anchor before starting unbound
    auto-trust-anchor-file: "/usr/local/etc/unbound/root.key"
    tls-cert-bundle: "/etc/ssl/cert.pem"

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.3@853#family.cloudflare-dns.com
    forward-addr: 1.0.0.3@853#family.cloudflare-dns.com
