#!/bin/bash

set -euo pipefail

container="golang:trixie"

docker_build() {
    lyrebird_ver="0.6.1"

    apt-get update -y
    apt-get upgrade -y
    apt-get install -y locales
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen

    tar xvf /src/lyrebird/lyrebird-lyrebird-${lyrebird_ver}.tar.gz -C /build/lyrebird
    cd /build/lyrebird/lyrebird-lyrebird-${lyrebird_ver}
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-X main.lyrebirdVersion=${LYREBIRD_VER}" -v -o lyrebird.exe ./cmd/lyrebird
    cp -v lyrebird.exe /src/lyrebird/
}

docker run --rm -v "$(pwd)":/src/lyrebird -w /build/lyrebird "${container}" bash -c "$(declare -f docker_build) && docker_build"
