#!/bin/sh

set -e

[ $# -ne 1 ] && exit 1

case $1 in
    -s) ;;
    -w) workstation=1 ;;
    *) exit 1 ;;
esac

pkgs="curl ssh git tar gzip"

[ -n "$workstation" ] && pkgs="$pkgs gpg"

for pkg in $pkgs; do
    [ -x "$(command -v "$pkg")" ] || missing_pkgs="$missing_pkgs $pkg"
done

if [ -n "$missing_pkgs" ]; then
    printf "Install missing packages:%s\n" "$missing_pkgs"
    exit 1
fi

cd "$HOME"

mkdir -m 700 .ssh
mkdir repos
mkdir .config

if [ -n "$workstation" ]; then
    curl -LO https://github.com/red-magic/dotfiles/raw/master/archive.tar.gz.gpg
    gpg -do archive.tar.gz archive.tar.gz.gpg
    tar xzf archive.tar.gz
    gpg --import archive/gpg/*.*
    printf "trust\n5\ny\nsave\n" | gpg --command-fd 0 --edit-key DB9A54FFE9854317497D69BB159C66B3104E3E30
    cp -f archive/ssh/id_ed25519 .ssh
    cp -f archive/ssh/id_ed25519.pub .ssh
    cp -f archive/ssh/id_ed25519.pub .ssh/authorized_keys
    touch .ssh/known_hosts
    chmod 600 .ssh/known_hosts
    rm -rf archive*

    curl -L https://github.com/red-magic/dotfiles/raw/master/.ssh/config -o .ssh/config
    chmod 400 .ssh/config
    eval "$(ssh-agent -s)"
    ssh-add
    git clone ssh://git@github.com/red-magic/dotfiles repos/dotfiles
    git clone ssh://git@github.com/red-magic/bible repos/bible
    if uname -s | grep -q Linux; then
        cp -rf repos/dotfiles/.docker .
        git clone ssh://git@github.com/red-magic/tty-colorscheme repos/tty-colorscheme
        git clone ssh://git@github.com/red-magic/cs16-server repos/cs16-server
        git clone ssh://git@github.com/red-magic/arti-bin repos/arti-bin
        if [ -f /etc/arch-release ]; then
            aur_pkgs="pacproxy-bin simple-and-soft-cursor snowflake-pt-client-bin tor-relay-scanner-bin ttf-go tty-colorscheme windows-10-cursor"
            mkdir repos/aur
            for aur_pkg in $aur_pkgs; do
                git clone "ssh://aur@aur.archlinux.org/$aur_pkg" "repos/aur/$aur_pkg"
            done
        fi
    fi

    mkdir .config/emacs
    cp -f repos/dotfiles/.config/emacs/init.el .config/emacs
    cp -f repos/dotfiles/.gitconfig .
fi

[ -z "$workstation" ] && git clone https://github.com/red-magic/dotfiles repos/dotfiles

mkdir .config/ranger
cp -f repos/dotfiles/.config/ranger/rc.conf .config/ranger

if uname -s | grep -q Linux; then
    cp -f repos/dotfiles/.bash_profile .
    cp -f repos/dotfiles/.bashrc .
elif uname -s | grep -q BSD; then
    cp -f repos/dotfiles/.profile .
    cp -f repos/dotfiles/.kshrc .
    cp -f repos/dotfiles/.mailrc .
    chmod 700 "$HOME"
    if [ -n "$workstation" ]; then
        cp -f repos/dotfiles/.cwmrc .
        cp -f repos/dotfiles/.xsession .
        cp -f repos/dotfiles/.Xdefaults .
        mkdir .fonts
        cp -rf repos/dotfiles/.fonts/Go .fonts
        cp -rf repos/dotfiles/pics .
    fi
fi
