#!/bin/sh

set -e

domain=domain.tld
domain_www=www.$domain

certbot certonly \
        --dry-run \
        --key-type ecdsa \
        --webroot \
        -w /var/www/$domain \
        -d $domain \
        -d $domain_www
