#!/bin/sh

set -e

if [ "$#" -ne 2 ]; then
    printf "Usage: %s <enc | enc-asym | dec> <file>\n" "$(basename "$0")"
    exit 1
fi

case "$1" in
    enc | enc-asym | dec)
        if [ ! -f "$2" ]; then
            printf "File %s doesn't exist\n" "$2"
            exit 1
        fi
        ;;
    *)
        printf "Invalid option: %s\n" "$1"
        exit 1
        ;;
esac

case "$1" in
    enc)
        if [ -f "$(basename "$2").gpg" ]; then
            printf "File %s already exists\n" "$(basename "$2").gpg"
            exit 1
        fi
        gpg -o "$(basename "$2").gpg" \
            --s2k-cipher-algo AES256 \
            --s2k-digest-algo SHA512 \
            --force-aead \
            --no-compress \
            -c "$2"
        ;;
    enc-asym)
        if [ -f "$(basename "$2").gpg" ]; then
            printf "File %s already exists\n" "$(basename "$2").gpg"
            exit 1
        fi
        gpg -o "$(basename "$2").gpg" \
            --cipher-algo AES256 \
            --digest-algo SHA512 \
            --force-aead \
            --no-compress \
            -es "$2"
        ;;
    dec)
        if [ -f "$(basename "$2" .gpg)" ]; then
            printf "File %s already exists\n" "$(basename "$2" .gpg)"
            exit 1
        fi
        gpg -do "$(basename "$2" .gpg)" "$2"
        ;;
esac
