#!/bin/sh

set -e

progname=$(basename "$0")

print_help()
{
    printf "usage: %s enc|dec file\n" "$progname"
}

if [ $# -gt 2 ]
then
    printf "%s: too many arguments\n" "$progname" >&2
    print_help
    exit 1
fi

cmd=$1
file=$2

case $cmd in
    enc | dec) ;;
    "")
        print_help
        exit 0
        ;;
    *)
        printf "%s: invalid command: %s\n" "$progname" "$cmd" >&2
        exit 1
        ;;
esac

if [ -z "$file" ]
then
    printf "%s: %s: missing file argument\n" "$progname" "$cmd" >&2
    print_help
    exit 1
fi

case $cmd in
    enc)
        file_dec=$file
        file_enc=$file.enc

        if [ ! -f "$file_dec" ]
        then
            printf "%s: %s: file %s doesn't exist\n" "$progname" "$cmd" "$file_dec" >&2
            exit 1
        fi

        if [ -f "$file_enc" ]
        then
            printf "%s: %s: file %s already exists\n" "$progname" "$cmd" "$file_enc" >&2
            exit 1
        fi
        ;;
    dec)
        case $file in
            *.enc) ;;
            *)
                printf "%s: %s: not a .enc file: %s\n" "$progname" "$cmd" "$file" >&2
                exit 1
                ;;
        esac

        file_enc=$file
        file_dec=${file%.enc}

        if [ ! -f "$file_enc" ]
        then
            printf "%s: %s: file %s doesn't exist\n" "$progname" "$cmd" "$file_enc" >&2
            exit 1
        fi

        if [ -f "$file_dec" ]
        then
            printf "%s: %s: file %s already exists\n" "$progname" "$cmd" "$file_dec" >&2
            exit 1
        fi
        ;;
esac

case $cmd in
    enc)
        openssl enc \
                -e \
                -aes-256-cbc \
                -md sha512 \
                -pbkdf2 \
                -iter 1000000 \
                -salt \
                -in "$file_dec" \
                -out "$file_enc"
        ;;
    dec)
        openssl enc \
                -d \
                -aes-256-cbc \
                -md sha512 \
                -pbkdf2 \
                -iter 1000000 \
                -salt \
                -in "$file_enc" \
                -out "$file_dec"
        ;;
esac
