#!/bin/sh

set -e

progname=$(basename "$0")

print_help()
{
    printf "usage: %s -e|-d file\n" "$progname"
}

if [ $# -gt 2 ]
then
    printf "%s: too many arguments\n" "$progname" >&2
    print_help
    exit 1
fi

mode=

case $1 in
    -e)
        mode=enc
        ;;
    -d)
        mode=dec
        ;;
    "")
        print_help
        exit 0
        ;;
    *)
        printf "%s: invalid option: %s\n" "$progname" "$1" >&2
        print_help
        exit 1
        ;;
esac

if [ -z "$mode" ]
then
    print_help
    exit 0
fi

file=$2

if [ -z "$file" ]
then
    printf "%s: %s: missing file argument\n" "$progname" "$1" >&2
    print_help
    exit 1
fi

case $mode in
    enc)
        file_dec=$file
        file_enc=$file.enc

        if [ ! -f "$file_dec" ]
        then
            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_dec" >&2
            exit 1
        fi

        if [ -f "$file_enc" ]
        then
            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_enc" >&2
            exit 1
        fi
        ;;
    dec)
        case $file in
            *.enc) ;;
            *)
                printf "%s: %s: not a .enc file: %s\n" "$progname" "$1" "$file" >&2
                exit 1
                ;;
        esac

        file_enc=$file
        file_dec=${file%.enc}

        if [ ! -f "$file_enc" ]
        then
            printf "%s: %s: file %s doesn't exist\n" "$progname" "$1" "$file_enc" >&2
            exit 1
        fi

        if [ -f "$file_dec" ]
        then
            printf "%s: %s: file %s already exists\n" "$progname" "$1" "$file_dec" >&2
            exit 1
        fi
        ;;
esac

case $mode in
    enc)
        openssl enc -e -aes-256-cbc -md sha512 -pbkdf2 -iter 1000000 -salt \
                -in "$file_dec" -out "$file_enc"
        ;;
    dec)
        openssl enc -d -aes-256-cbc -md sha512 -pbkdf2 -iter 1000000 -salt \
                -in "$file_enc" -out "$file_dec"
        ;;
esac
