#!/bin/sh

set -e

print_help() {
    printf "usage: %s enc|dec file\n" "$(basename "$0")"
}

if [ $# -gt 2 ]; then
    printf "%s: too many arguments\n" "$(basename "$0")" >&2
    print_help
    exit 1
fi

case $1 in
    enc | dec)
        if [ -z "$2" ]; then
            printf "%s: %s: missing file argument\n" "$(basename "$0")" "$1" >&2
            print_help
            exit 1
        elif [ ! -f "$2" ]; then
            printf "%s: %s: file %s doesn't exist\n" "$(basename "$0")" "$1" "$2" >&2
            exit 1
        fi
        ;;
    "")
        print_help
        exit 0
        ;;

    *)
        printf "%s: invalid command: %s\n" "$(basename "$0")" "$1" >&2
        exit 1
        ;;
esac

case $1 in
    enc)
        if [ -f "$(basename "$2").enc" ]; then
            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2").enc" >&2
            exit 1
        fi
        openssl enc \
                -e \
                -aes-256-cbc \
                -md sha512 \
                -pbkdf2 \
                -iter 1000000 \
                -salt \
                -in "$2" \
                -out "$(basename "$2").enc"
        ;;
    dec)
        if [ -f "$(basename "$2" .enc)" ]; then
            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2" .enc)" >&2
            exit 1
        fi
        openssl enc \
                -d \
                -aes-256-cbc \
                -md sha512 \
                -pbkdf2 \
                -iter 1000000 \
                -salt \
                -in "$2" \
                -out "$(basename "$2" .enc)"
        ;;
esac
