#!/bin/sh

set -e

progname=$(basename "$0")

print_help()
{
    printf "usage: %s enc|enc-asym|dec file\n" "$progname"
}

if [ $# -gt 2 ]
then
    printf "%s: too many arguments\n" "$progname" >&2
    print_help
    exit 1
fi

cmd=$1
file=$2

case $cmd in
    enc | enc-asym | dec) ;;
    "")
        print_help
        exit 0
        ;;
    *)
        printf "%s: invalid command: %s\n" "$progname" "$cmd" >&2
        exit 1
        ;;
esac

if [ -z "$file" ]
then
    printf "%s: %s: missing file argument\n" "$progname" "$cmd" >&2
    print_help
    exit 1
fi

case $cmd in
    enc | enc-asym)
        file_dec=$file
        file_enc=$file.gpg

        if [ ! -f "$file_dec" ]
        then
            printf "%s: %s: file %s doesn't exist\n" "$progname" "$cmd" "$file_dec" >&2
            exit 1
        fi

        if [ -f "$file_enc" ]
        then
            printf "%s: %s: file %s already exists\n" "$progname" "$cmd" "$file_enc" >&2
            exit 1
        fi
        ;;
    dec)
        case $file in
            *.gpg) ;;
            *)
                printf "%s: %s: not a .gpg file: %s\n" "$progname" "$cmd" "$file" >&2
                exit 1
                ;;
        esac

        file_enc=$file
        file_dec=${file%.gpg}

        if [ ! -f "$file_enc" ]
        then
            printf "%s: %s: file %s doesn't exist\n" "$progname" "$cmd" "$file_enc" >&2
            exit 1
        fi

        if [ -f "$file_dec" ]
        then
            printf "%s: %s: file %s already exists\n" "$progname" "$cmd" "$file_dec" >&2
            exit 1
        fi
        ;;
esac

case $cmd in
    enc)
        gpg -o "$file_enc" \
            --s2k-cipher-algo AES256 \
            --s2k-digest-algo SHA512 \
            --force-aead \
            --no-compress \
            -c "$file_dec"
        ;;
    enc-asym)
        gpg -o "$file_enc" \
            --cipher-algo AES256 \
            --digest-algo SHA512 \
            --force-aead \
            --no-compress \
            -es "$file_dec"
        ;;
    dec)
        gpg -do "$file_dec" "$file_enc"
        ;;
esac
