#!/bin/sh

set -e

print_help() {
    printf "usage: %s enc|enc-asym|dec file\n" "$(basename "$0")"
}

if [ $# -gt 2 ]; then
    printf "%s: too many arguments\n" "$(basename "$0")" >&2
    print_help
    exit 1
fi

case $1 in
    enc | enc-asym | dec)
        if [ -z "$2" ]; then
            printf "%s: %s: missing file argument\n" "$(basename "$0")" "$1" >&2
            print_help
            exit 1
        elif [ ! -f "$2" ]; then
            printf "%s: %s: file %s doesn't exist\n" "$(basename "$0")" "$1" "$2" >&2
            exit 1
        fi
        ;;
    "")
        print_help
        exit 0
        ;;

    *)
        printf "%s: invalid command: %s\n" "$(basename "$0")" "$1" >&2
        exit 1
        ;;
esac

case $1 in
    enc)
        if [ -f "$(basename "$2").gpg" ]; then
            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2").gpg" >&2
            exit 1
        fi
        gpg -o "$(basename "$2").gpg" \
            --s2k-cipher-algo AES256 \
            --s2k-digest-algo SHA512 \
            --force-aead \
            --no-compress \
            -c "$2"
        ;;
    enc-asym)
        if [ -f "$(basename "$2").gpg" ]; then
            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2").gpg" >&2
            exit 1
        fi
        gpg -o "$(basename "$2").gpg" \
            --cipher-algo AES256 \
            --digest-algo SHA512 \
            --force-aead \
            --no-compress \
            -es "$2"
        ;;
    dec)
        if [ -f "$(basename "$2" .gpg)" ]; then
            printf "%s: %s: file %s already exists\n" "$(basename "$0")" "$1" "$(basename "$2" .gpg)" >&2
            exit 1
        fi
        gpg -do "$(basename "$2" .gpg)" "$2"
        ;;
esac
