#!/bin/sh

set -e

progname=$(basename "$0")

if [ $# -gt 1 ]
then
    printf "%s: only 1 argument is accepted\n" "$progname" >&2
    print_help
    exit 1
elif [ $# -eq 0 ]
then
    printf "usage: %s directory\n" "$progname"
    exit 0
fi

dir=$1

if [ ! -d "$dir" ]
then
    printf "%s: no such directory: %s\n" "$progname" "$dir" >&2
    exit 1
fi

find "$dir" -type f | while IFS= read -r file
do
    if grep -Iq . "$file"
    then
        if grep -q "$(printf '\r\n')" "$file"
        then
            printf "CRLF: %s\n" "$file"
        elif grep -q "$(printf '\n')" "$file"
        then
            printf "LF:   %s\n" "$file"
        fi
    fi
done
