#!/bin/sh

set -e

progname=$(basename "$0")

if [ -z "$1" ]
then
    printf "usage: %s directory\n" "$progname"
    exit 0
fi

dir=$1

if [ ! -d "$dir" ]
then
    printf "%s: no such directory: %s\n" "$progname" "$dir" >&2
    exit 1
fi

find "$dir" -type f -exec sh -c 'last=$(tail -c 1 "$1"); [ -n "$last" ] && [ "$last" != "$(printf "\n")" ] && [ "$last" != "$(printf "\r")" ] && echo "No line terminator at eof: '\''$1'\''"' _ {} \;
