#!/bin/sh

set -e

progname=$(basename "$0")

if [ -z "$1" ]
then
    printf "usage: %s directory\n" "$progname"
    exit 0
fi

dir=$1

if [ ! -d "$dir" ]
then
    printf "%s: no such directory: %s\n" "$progname" "$dir" >&2
    exit 1
fi

grep -rIn '[[:space:]]$' "$dir" | \
    while IFS=: read -r file line text
    do
        printf "trailing whitespaces: %s:%s: %s\n" "$file" "$line" "$text"
    done
