#!/bin/sh

set -e

progname=$(basename "$0")

if [ -z "$1" ]
then
    printf "usage: %s directory\n" "$progname"
    exit 0
fi

dir=$1

if [ ! -d "$dir" ]
then
    printf "%s: no such directory: %s\n" "$progname" "$dir" >&2
    exit 1
fi

find "$dir" -type f -exec /bin/sh -c '
    last=$(tail -c 1 "$1" 2>/dev/null) || exit 0
    case $last in
        "" | "$(printf "\n")" | "$(printf "\r")")
            ;;
        *)
            printf "no line terminator at EOF: %s\n" "$1"
            ;;
    esac
' /bin/sh {} \;
