#!/bin/sh

set -e

progname=${0##*/}

if [ $# -gt 1 ]
then
    printf "%s: only 1 argument is accepted\n" "$progname" 1>&2
    print_help
    exit 1
elif [ $# -eq 0 ]
then
    printf "usage: %s directory\n" "$progname"
    exit 0
fi

dir=$1

if [ ! -d "$dir" ]
then
    printf "%s: no such directory: %s\n" "$progname" "$dir" 1>&2
    exit 1
fi

grep -rIn '[[:space:]]$' "$dir" | while IFS=: read -r file line text
do
    printf "trailing whitespaces: %s:%s: %s\n" "$file" "$line" "$text"
done
