#!/bin/sh

_package-check() {
	PACKAGES[0]=bash
	PACKAGES[1]=curl
	PACKAGES[2]=ssh
	PACKAGES[3]=git
	PACKAGES[4]=xz
	PACKAGES[5]=tar

	if [[ $ISWORKSTATION == "yes" ]]; then
		PACKAGES[6]=gpg
	fi

	for PKG in ${PACKAGES[@]}; do
		if ! [[ -x "$(command -v $PKG)" ]]; then
			TOINSTALL="$TOINSTALL $PKG"
		fi
	done

	if [[ $TOINSTALL != "" ]]; then
		echo Install packages $TOINSTALL;
		exit $1;
	fi
}

_init-config() {
	#rm -rf * .*
	mkdir -m 700 .ssh
	mkdir repos
}

_git-config() {
	if [[ -f .ssh/id_ed25519 ]]; then
		git clone git@github.com:red-magic/dotfiles repos/dotfiles
	else
		git clone https://github.com/red-magic/dotfiles repos/dotfiles
	fi

	cp -f repos/dotfiles/.gitconfig .

	if [[ $(uname | grep BSD) != "" ]]; then
		cp -f repos/dotfiles/.other/.profile .
	else
		cp -f repos/dotfiles/.bash_profile .
		ln -sf .bash_profile .bashrc
	fi
}

workstation-config() {
	ISWORKSTATION=yes

	cd ~/

	_package-check
	_init-config

	gpg --keyserver keyserver.ubuntu.com --search-keys 127D297F
	gpg --edit-key 127D297F trust
	curl -L https://github.com/red-magic/dotfiles/raw/master/.archive.tar.xz.gpg -o archive.tar.xz.gpg
	gpg -do archive.tar.xz archive.tar.xz.gpg
	unxz archive.tar.xz
	tar xvf archive.tar
	gpg --import archive/ssh-gpg/e*
	cp -f archive/ssh-gpg/id* .ssh/
	rm -rf archive*
	rm -f .ssh/*.ppk
	cp -f .ssh/*.pub .ssh/authorized_keys
	touch .ssh/known_hosts
	chmod 600 .ssh/known_hosts

	_git-config
}

server-config() {
	cd ~/

	_package-check
	_init-config

	curl -LO https://github.com/red-magic.keys
	sed -i "s/$/ $USER/" red-magic.keys
	mv -f red-magic.keys .ssh/authorized_keys
	chmod 400 .ssh/authorized_keys

	_git-config
	
	if [[ -f .bash_profile ]]; then
		sed -i 27q .bash_profile
	fi
}

case $1 in
	"workstation")
		workstation-config
		;;
	"server")
		server-config
		;;
esac
