#!/bin/sh

set -e

progname=$(basename "$0")

qemu_cmd=qemu-system-x86_64
qemu_args="-cpu host -smp 16 -m 8G -net nic -net user,hostfwd=tcp::2222-:22 -audio driver=pa,id=pa1,model=hda"
cd_args=
drive_args=

print_help()
{
    printf "usage: %s [-d system.img] [-c cd.iso]\n" "$progname"
}

while getopts :d:c: opt
do
    # -enable-kvm Linux
    # -enable-vvm OpenBSD
    case $opt in
        c)
            cd_args="-cdrom '$OPTARG'"
            ;;
        d)
            drive_args="-drive 'file=$OPTARG,format=raw'"
            ;;
        :)
            printf "%s: option -%s requires an argument\n" "$progname" "$OPTARG" >&2
            print_help
            exit 1
            ;;
        *)
            printf "%s: invalid option: -%s\n" "$progname" "$OPTARG" >&2
            print_help
            exit 1
            ;;
    esac
done

if [ -z "$drive_args" ] && [ -z "$cd_args" ]
then
    print_help
    exit 0
fi

printf "%s %s %s %s\n" "$qemu_cmd" "$qemu_args" "$drive_args" "$cd_args"
eval "$qemu_cmd $qemu_args $drive_args $cd_args"
