#!/bin/bash

set -euo pipefail

if [[ -z "${1:-}" ]]; then
    printf "Usage: %s <directory>\n" "$(basename "${0}")"
    exit 1
fi

target_dir="${1}"

cd "${target_dir}"

for file in *; do
    if [[ -f "${file}" ]]; then
        extension="${file##*.}"
        if [[ "${extension}" != "${file}" ]]; then
            newname="$(head -c 256 /dev/urandom | sha256sum | awk '{print $1}' | head -c 32)"
            mv -vn -- "${file}" "${newname}.${extension}"
        fi
    fi
done
