#!/bin/sh

set -e

progname=$(basename "$0")

if [ -z "$1" ]
then
    printf "usage: %s directory\n" "$progname"
    exit 1
fi

os_name=$(uname -s)

case $os_name in
    *BSD)
        sha_cmd=sha256
        ;;
    Linux)
        sha_cmd=sha256sum
        ;;
    *)
        printf "%s: unable to detect OS for \$sha_cmd\n" "$progname" >&2
        exit 1
        ;;
esac

target_dir=$1

cd "$target_dir"

for file in *
do
    if [ -f "$file" ]
    then
        ext="${file##*.}"
        if [ "$ext" != "$file" ]
        then
            newname=$(dd if=/dev/urandom bs=256 count=1 2> /dev/null | $sha_cmd | cut -c 1-32)
            mv -vf -- "$file" "$newname.$ext"
        fi
    fi
done
