#!/bin/sh

set -e

if [ -z "$1" ]; then
    printf "Usage: %s <directory>\n" "$(basename "$0")"
    exit 1
fi

os_name="$(uname -s)"

case "$os_name" in
    *BSD)
        sha_cmd=sha256
        ;;
    Linux)
        sha_cmd=sha256sum
        ;;
    *)
        printf "Unable to detect OS for \$sha_cmd\n"
        exit 1
        ;;
esac

cd "$1"

for file in *; do
    if [ -f "$file" ]; then
        extension="${file##*.}"
        if [ "$extension" != "$file" ]; then
            newname=$(dd if=/dev/urandom bs=256 count=1 2> /dev/null | $sha_cmd | cut -c 1-32)
            mv -vf -- "$file" "$newname.$extension"
        fi
    fi
done
