#!/bin/sh

set -e

username=username

mkdir libera

openssl req \
        -x509 \
        -newkey ed25519 \
        -sha256 \
        -nodes \
        -days 1825 \
        -subj "/CN=$username" \
        -out libera/libera.pem \
        -keyout libera/libera.pem

chmod 400 libera/libera.pem

openssl x509 \
        -in libera/libera.pem \
        -text \
        -noout

openssl x509 \
        -in libera/libera.pem \
        -noout \
        -fingerprint -sha512 \
    | awk -F= '{gsub(":",""); print tolower ($2)}' > libera/libera.fp

chmod 444 libera/libera.fp

cat libera/libera.fp
