#!/bin/sh

set -e

mkdir libera

if [ ! -f irc.pem ]
then
    openssl req \
            -x509 \
            -newkey RSA \
            -pkeyopt rsa_keygen_bits:4096 \
            -sha384 \
            -nodes \
            -days 1825 \
            -subj "/CN=irc.libera.chat" \
            -out libera/libera.pem \
            -keyout libera/libera.pem
fi

chmod 400 libera/libera.pem

openssl x509 \
        -in libera/libera.pem \
        -text \
        -noout

openssl x509 \
        -in libera/libera.pem \
        -noout \
        -fingerprint -sha512 \
    | awk -F= '{gsub(":",""); print tolower ($2)}' > libera/libera.fp

chmod 444 libera/libera.fp

cat libera/libera.fp
