#!/bin/sh

set -e

c_name=AQ
o_name=Internal
cn_name=domain.internal

valid_days=7300

mkdir $cn_name

openssl req \
        -x509 \
        -newkey EC \
        -pkeyopt ec_paramgen_curve:secp384r1 \
        -sha384 \
        -nodes \
        -days $valid_days \
        -subj "/C=$c_name/O=$o_name/CN=$cn_name" \
        -addext "keyUsage = critical, digitalSignature" \
        -addext "extendedKeyUsage = serverAuth" \
        -addext "basicConstraints = critical, CA:FALSE" \
        -addext "subjectKeyIdentifier = hash" \
        -addext "subjectAltName = DNS:$cn_name" \
        -set_serial "0x$(openssl rand -hex 16)" \
        -keyout $cn_name/$cn_name.key \
        -out $cn_name/$cn_name.crt

chmod 400 $cn_name/$cn_name.key
chmod 444 $cn_name/$cn_name.crt

openssl x509 -in $cn_name/$cn_name.crt -text -noout
