#!/bin/sh

set -e

c_name=AQ
o_name="Libera Chat"
cn_name=nickname

mkdir libera

openssl req \
        -x509 \
        -newkey ed25519 \
        -sha256 \
        -days 7300 \
        -nodes \
        -subj "/C=$c_name/O=$o_name/CN=$cn_name" \
        -set_serial "0x$(openssl rand -hex 16)" \
        -keyout libera/libera.pem \
        -out libera/libera.pem

chmod 400 libera/libera.pem

openssl x509 \
        -in libera/libera.pem \
        -text \
        -noout

openssl x509 \
        -in libera/libera.pem \
        -noout \
        -fingerprint -sha512 \
    | awk -F= '{gsub(":",""); print tolower ($2)}' > libera/libera.sha512

chmod 444 libera/libera.sha512

cat libera/libera.sha512
