#!/bin/bash

case "${1}" in
    "build")
        docker build --progress plain -t cs16-server-net .
        ;;
    "deploy")
        docker run --init -d -p 27015:27015/udp -p 27015:27015 --name cs16-server-net cs16-server-net
        ;;
    "start")
        docker start cs16-server-net
        ;;
    "stop")
        docker stop cs16-server-net
        ;;
    "restart")
        docker restart cs16-server-net
        ;;
esac
