#!/bin/bash

rm -f ~/.git/index.lock

git add -f	~/txts							\
		~/.config/user-dirs.dirs				\
		~/.config/ranger/rc.conf				\
		~/.ncmpcpp/config					\
		~/themes						\
		~/.icons						\
		~/.fonts/MaterialIcons-Regular.ttf			\
		~/.old							\
		~/scripts						\
		~/.local/share/applications/theme*			\
		~/.local/share/applications/tarxz-backup.desktop	\
		~/.local/share/applications/git-track.desktop		\
		~/.local/share/applications/tremc.desktop		\
		~/.local/share/applications/movies.desktop		\
		~/.xinitrc						\
		~/.bashrc						\
		~/.gitignore						\
		~/.gitconfig						\
		~/.weechat/weechat.conf					\
		~/.weechat/irc.conf					\
		~/.config/polybar/polybar.sh				\
		~/.config/mpv						\
		~/.cataclysm-dda/config/custom_colors.json		\
		~/.tmux.conf
