#!/bin/bash

trap control_c SIGINT
trap control_c SIGTERM

function control_c {
	rm -fv ~/backup.*
    	echo -e "\n\n==> Aborted.\n" && read -pr ""
	exit $?
}

function megabackup {
	tput sgr0
	read -pr "Mega email: " -s megaemail
	read -pr "Mega password: " -s megapassword
	echo
	megarm /Root/backups -u "$megaemail" -p "$megapassword"
	megamkdir /Root/backups -u "$megaemail" -p "$megapassword"
	echo
	megacopy -l ~/backups/ -r /Root/backups -u "$megaemail" -p "$password"
	echo
}

function backup {
	rm -fv ~/backup.*
	tput sgr0
	tput setaf 4 && tput bold
	tar cvf ~/backup.tar 	\
		~/pictures	\
		~/programs
	echo
	echo -e "\e[31m\e[1m==> Compressing\e[0m"
	echo
	tput sgr0 && tput setaf 6 && tput bold
	xz -vv --lzma2=preset=9e,dict=64M,pb=0,lc=4 -T 8 ~/backup.tar
	gpg -cs --s2k-cipher-algo AES256 --s2k-digest-algo SHA512 --s2k-count 65536 ~/backup.tar.xz
	sha512sum backup.tar.xz > backup.tar.xz.sha512
	rm -fv ~/backup.tar
	rm -fv ~/backup.tar.xz
	mv -fv ~/backup.tar.xz.gpg ~/backups/backup.tar.xz.gpg
	mv -fv ~/backup.tar.xz.sha512 ~/backups/backup.tar.xz.sha512
	echo
	megabackup
	echo -e "\e[31m\e[1m==> Done\e[0m" && read -pr ""
}

backup
