#!/bin/sh

cp -f ~/themes/dark/.Xresources ~/.Xresources
cp -f ~/themes/dark/i3/config ~/.config/i3/config
cp -f ~/themes/dark/polybar/config ~/.config/polybar/config
cp -f ~/themes/dark/.gtkrc-2.0 ~/.gtkrc-2.0
cp -f ~/themes/dark/settings.ini ~/.config/gtk-3.0/settings.ini
xrdb ~/.Xresources
i3-msg restart
