#!/bin/sh

cp -f ~/themes/purple/.Xresources ~/.Xresources
cp -f ~/themes/purple/i3/config ~/.config/i3/config
cp -f ~/themes/purple/polybar/config ~/.config/polybar/config
cp -f ~/themes/purple/.gtkrc-2.0 ~/.gtkrc-2.0
cp -f ~/themes/purple/settings.ini ~/.config/gtk-3.0/settings.ini
xrdb ~/.Xresources
i3-msg restart
