#!/bin/sh

cp -f ~/themes/ibm-plex-darker/.Xresources ~/.Xresources
cp -f ~/themes/ibm-plex-darker/i3/config ~/.config/i3/config
cp -f ~/themes/ibm-plex-darker/polybar/config ~/.config/polybar/config
cp -f ~/themes/ibm-plex-darker/.gtkrc-2.0 ~/.gtkrc-2.0
cp -f ~/themes/ibm-plex-darker/settings.ini ~/.config/gtk-3.0/settings.ini
xrdb ~/.Xresources
i3-msg restart
