#!/bin/bash

set -euo pipefail

container="rust:slim-trixie"

docker_build() {
    arti_ver="1.5.0"

    apt-get update -y
    apt-get install -y pkg-config libssl-dev libsqlite3-dev

    tar xvf /src/arti/arti-arti-v${arti_ver}.tar.gz -C /build/arti
    cd arti-arti-v${arti_ver}
    cargo build -p arti --locked --release
    strip -sv target/release/arti
    cp -v target/release/arti /src/arti
}

docker run --rm -v "$(pwd)":/src/arti -w /build/arti "${container}" bash -c "$(declare -f docker_build) && docker_build"
