#!/bin/bash

colorschemes_dir="colorschemes"

print_colored_block() {
	hex_color="$1"
	printf "\e[48;2;$(printf "%d;%d;%d" 0x"${hex_color:0:2}" 0x"${hex_color:2:2}" 0x"${hex_color:4:2}")m   \e[0m"
}

print_colorschemes() {
	for scheme in "$colorschemes_dir"/*; do
		scheme_name=$(basename "$scheme")
		echo "$scheme_name"
		source "$scheme"
		if [[ -n "$colored" ]]; then
			counter=0
			for i in {1..16}; do
				hex_value="color$i"
				print_colored_block "${!hex_value}"
				((counter++))
				if ((counter % 8 == 0)); then
					echo
				fi
			done
		fi
	done
}

set_tty_color() {
	echo -en "\e]P0${tty_color[0]}"  # Background
	echo -en "\e]P1${tty_color[1]}"  # Red
	echo -en "\e]P2${tty_color[2]}"  # Green
	echo -en "\e]P3${tty_color[3]}"  # Yellow
	echo -en "\e]P4${tty_color[4]}"  # Blue
	echo -en "\e]P5${tty_color[5]}"  # Magenta
	echo -en "\e]P6${tty_color[6]}"  # Cyan
	echo -en "\e]P7${tty_color[7]}"  # White
	echo -en "\e]P8${tty_color[8]}"  # Black
	echo -en "\e]P9${tty_color[9]}"  # Red
	echo -en "\e]PA${tty_color[10]}" # Green
	echo -en "\e]PB${tty_color[11]}" # Yellow
	echo -en "\e]PC${tty_color[12]}" # Blue
	echo -en "\e]PD${tty_color[13]}" # Magenta
	echo -en "\e]PE${tty_color[14]}" # Cyan
	echo -en "\e]PF${tty_color[15]}" # White
}

set_tty_colorscheme() {
	if [[ -z "$colorscheme" ]]; then
		colorscheme="$1"
	fi
	if [[ -v color_scheme[$colorscheme] ]]; then
		IFS=" " read -r -a tty_color <<< "${color_scheme[$colorscheme]}"
		for i in {1..6}; do
			set_tty_color > /dev/tty"${i}"
		done
		if [[ "$TERM" == "linux" ]]; then
			clear
		fi
		echo "Setting $colorscheme colorscheme"
	else
		echo "Invalid colorscheme provided"
		exit 1
	fi
}

print_help() {
	echo "Usage: tty-colors [color_scheme]"
	echo "  -l    list colorschemes"
	echo "  -p    list colorschemes and print colors"
#	echo "  -c    <config_file>"
	echo "  -h    print help"
}

if [ $# -eq 0 ]; then
	print_help
fi

while getopts ":hlpc:" opt; do
	case "${opt}" in
		h) print_help;;
		l) print_colorschemes;;
		p) colored="y" print_colorschemes;;
#		c) source "$OPTARG" && set_tty_colorscheme;;
		:) echo "Usage: -c <config_file>" && exit 1;;
		\?) echo "Invalid option" && exit 1;;
	esac
done

shift $((OPTIND -1))

if [ $# -eq 1 ]; then
	set_tty_colorscheme "$1"
fi
