[bridges]
enabled = true
bridges = '''
Bridge obfs4 176.169.236.210:4431 F829D395093B4469808CE7A660AD33AC391FB64A cert=CGZxQnDVoqNLSyERUV5Wf1AklsRCwwSbLbeWjS7Aea6weFwQceg6XnEiXtKEdvWOxm1dMw iat-mode=0
Bridge obfs4 185.177.207.57:13630 A3D55AA6178E80AE486B6DAEAFBA5AB79B29B399 cert=p9L6+25s8bnfkye1ZxFeAE4mAGY7DH4Gaj7dxngIIzP9BtqrHHwZXdjMK0RVIQ34C7aqZw iat-mode=2
'''

[[bridges.transports]]
protocols = ["obfs4"]
path = "/home/user/.local/bin/obfs4proxy"
arguments = []
run_on_startup = true
