#!/bin/sh 

if [ "$(id -u)" -ne 0 ]; then
	printf 'Use sudo to run this script\n'
	exit 1
fi

server_user=
steam_dir=/home/$server_user/.steam
server_conf=

case $1 in
	start)
		eval "$(grep '^server_params' "$server_conf")"
		su "$server_user" -c "cd $steam_dir/cs16 && ./hlds_run ${server_params:?} &> /dev/null &"
		;;
	restart)
		su "$server_user" -c "kill $(pgrep hlds_run) &> /dev/null"
		su "$server_user" -c "kill $(pgrep hlds_linux) &> /dev/null"
		eval "$(grep '^server_params' "$server_conf")"
		su "$server_user" -c "cd $steam_dir/cs16 && ./hlds_run ${server_params:?} &> /dev/null &"
		;;
	stop)
		su "$server_user" -c "kill $(pgrep hlds_run)"
		su "$server_user" -c "kill $(pgrep hlds_linux)"
		;;
	update)
		su "$server_user" -c "cd $steam_dir && ./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit"
		;;
	-h | --help | *) printf 'Usage: %s [start | restart | stop | update]\n' "$(basename "$0")" && exit 1;;
esac
