#!/bin/sh 

if [ "$(id -u)" -ne 0 ]; then
	printf 'Use sudo to run this script\n'
	exit 1
fi

server_user=
steam_dir=/home/$server_user/.steam
server_dir=$steam_dir/cs16
server_conf=

case $1 in
	start) # Run in background
		eval "$(grep server_params "$server_conf")"
		su "$server_user" -c "$server_dir/hlds_run ${server_params:?} &> /dev/null &"
		;;
	restart)
		su "$server_user" -c "kill $(pgrep hlds_linux)"
		;;
	stop)
		su "$server_user" -c "kill $(pgrep hlds_run)"
		su "$server_user" -c "kill $(pgrep hlds_linux)"
		;;
	update)
		su "$server_user" -c "$steam_dir/steamcmd.sh +force_install_dir $server_dir +login anonymous +app_update 90 validate +quit"
		# Ater earch update liblist.gam reverts to default so we need to include metamod.so in it
		su "$server_user" -c "sed -i 's/gamedll_linux \"dlls\/cs.so\"/gamedll_linux \"addons\/metamod\/dlls\/metamod.so\"/g' $steam_dir/cstrike/liblist.gam"
		;;
	-h | --help | *) printf 'Usage: %s [start | restart | stop | update]\n' "$(basename "$0")" && exit 1;;
#	start)
#		su "$server_user" -c "cd $server_dir && ./hlds_run $server_params"
#		;;
#	"start-screen")
#		su "$server_user" -c "cd $server_dir && screen -m -d -S cs16 ./hlds_run $server_params"
#		;;
#	"restart-screen")
#		su "$server_user" -c "cd $server_dir && kill $(pgrep screen)"
#		su "$server_user" -c "cd $server_dir && screen -m -d -S cs16 ./hlds_run $server_params"
#		;;
#	"stop-screen")
#		su "$server_user" -c "kill $(pgrep screen)"
#		;;
#	"screen")
#		su "$server_user" -c "screen -r"
#		;;
esac
