#!/bin/bash

start() {
	for i in {1..6}; do
		echo -en "\e]P0F5F5F5" > /dev/tty"${i}" # Background
		echo -en "\e]P1212121" > /dev/tty"${i}" # Red
		echo -en "\e]P2212121" > /dev/tty"${i}" # Green
		echo -en "\e]P3212121" > /dev/tty"${i}" # Yellow
		echo -en "\e]P4212121" > /dev/tty"${i}" # Blue
		echo -en "\e]P5212121" > /dev/tty"${i}" # Magenta
		echo -en "\e]P6212121" > /dev/tty"${i}" # Cyan
		echo -en "\e]P7212121" > /dev/tty"${i}" # White
		echo -en "\e]P8F5F5F5" > /dev/tty"${i}" # Black
		echo -en "\e]P9212121" > /dev/tty"${i}" # Red
		echo -en "\e]PA212121" > /dev/tty"${i}" # Green
		echo -en "\e]PB212121" > /dev/tty"${i}" # Yellow
		echo -en "\e]PC212121" > /dev/tty"${i}" # Blue
		echo -en "\e]PD212121" > /dev/tty"${i}" # Magenta
		echo -en "\e]PE212121" > /dev/tty"${i}" # Cyan
		echo -en "\e]PF212121" > /dev/tty"${i}" # White
	done
}; start 
